// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk0e6-SWdIJYdgh0YGls9uJ05SBYzxlKo',
    appId: '1:953590213666:web:a7069cbd0ade5d18db6e7b',
    messagingSenderId: '953590213666',
    projectId: 'docterapp-5b393',
    authDomain: 'docterapp-5b393.firebaseapp.com',
    storageBucket: 'docterapp-5b393.firebasestorage.app',
    measurementId: 'G-3M7W926PKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALSHgpOKAf54hXxkgqSuyrYY1m2mfOaZE',
    appId: '1:953590213666:android:b76258ce1b3620dcdb6e7b',
    messagingSenderId: '953590213666',
    projectId: 'docterapp-5b393',
    storageBucket: 'docterapp-5b393.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEvA7HCx4uH02c13Y5VL_mq-AhJK89ZJw',
    appId: '1:953590213666:ios:15e9bd320767dd9cdb6e7b',
    messagingSenderId: '953590213666',
    projectId: 'docterapp-5b393',
    storageBucket: 'docterapp-5b393.firebasestorage.app',
    iosClientId: '953590213666-aoij6aiafet81olq7qd6vqcstg6epuu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.docterapp',
  );
}
